server:
   port: 8080
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/activiti?useSSL=false&characterEncoding=UTF8&serverTimezone=UTC
      username: root
      password: root
   thymeleaf:
      cache: false
      enabled: true
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   resources:
      add-mappings: true
   mvc:
      hiddenmethod: 
         filter: 
            enabled: true
mybatis:
   map-underscore-to-camel-case: true
xzh:
   noAuthUrls:
   - /
   - /login
   - /logout
   - /captcha