server:
  port: 8080

spring:
  application:
    name: xzh-log
  datasource:
    url: jdbc:mysql://xuzhihao:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
   
logging:
  level:
    root: info
    net.xzh: debug
    
xzh:
  audit-log:
    enabled: true
    log-type: db
    datasource: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://xuzhihao:3306/logger-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: root