server:
  port: 8080

spring:
  application:
    name: xzh-oss
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/file_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
   
logging:
  level:
    root: info
    net.xzh: debug
    
xzh:
  file-server:
    type: s3
    fdfs:
      web-url: http://xuzhihao
    s3:
      access-key: minioadmin
      accessKeySecret: minioadmin
      endpoint: http://xuzhihao:9000
      bucketName: test
fdfs: 
   trackerList: xuzhihao:22122