server:
   port: 8080
hbase:
   config:
      hbase.zookeeper.quorum: 172.17.17.161
      hbase.zookeeper.port: 2181
      hbase.zookeeper.znode: /hbase
      hbase.client.keyvalue.maxsize: 1572864000