sharding:
  jdbc:
    datasource:
      names: ds-0,ds-1
      ds-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.17.17.29:5432/ec_demo_0?useUnicode=true&characterEncoding=utf8&currentSchema=public&stringtype=unspecified
        username: postgres
        password: vjsp2020
      ds-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.17.17.29:5432/ec_demo_1?useUnicode=true&characterEncoding=utf8&currentSchema=public&stringtype=unspecified
        username: postgres
        password: vjsp2020
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds-$->{user_id % 2}
        tables:
          order:
            actual-data-nodes: ds-$->{0..1}.order$->{0..4}
            table-strategy:
              inline:
                sharding-column: user_id
                algorithm-expression: order$->{(user_id % 5)}
            key-generator-column-name: user_id
          user_info:
            actual-data-nodes: ds-$->{0..1}.user_info
            key-generator-column-name: id
        broadcast-tables: area
      props:
        sql:
          show: true